### ISSUE TITLE
Set/Get race condition

### ISSUE THREAD

**Issue by merpnderp** [chill117/express-mysql-session#10]
Is a patch to make sure that if a set is called on an SID that no gets return that SID until the set has returned something anyone would want? 

I ran into this issue in my own mysqlstore when my client and node server were on the same machine and my DB was on another high latency server. My node instance called the set, redirected my client, then called a get which returned before the set had finished, giving me a new user login bug.

**Comment by chill117** [comment]
This is something that should probably be handled at the application layer, no? Unless I am mis-understanding what problem you're describing.

**Comment by merpnderp** [comment]
Yes, that's actually how I corrected it and after I did it became obvious that's where it belonged. Thanks for the response :)

**Comment by chill117** [comment]
Glad to hear that things worked out :)
