### ISSUE TITLE
how increase expiration time of the saved session to more than one day?

### ISSUE THREAD

**Issue by moahammadalt** [chill117/express-mysql-session#102]

**Comment by etisdew** [comment]
Sorry because I'm not an authority on the issue but do the documentations comment on the expiration options not work in practice?

**Comment by etisdew** [comment]
Perhaps you wouldnt mind closing the issue if you no longer wish to follow up? To be clear perhaps you were interested in the format of time being employed. Take the number of seconds you desire and multiply that by one thousand.

**Comment by chill117** [comment]
It is possible to change the default expiration time using the `expiration` option as shown in [the readme](https://github.com/chill117/express-mysql-session#options):
> 	// The maximum age of a valid session; milliseconds:
>	expiration: 86400000,
