### ISSUE TITLE
In memory cache?

### ISSUE THREAD

**Issue by SanjayTCP** [chill117/express-mysql-session#103]
I'm curious if this could benefit from an optional in memory cache. If a session is found in memory we could avoid the round trip to the DB. I'm happy to PR, I was wondering thoughts?

**Comment by etisdew** [comment]
If you are presently using this proposal I would be open to reviewing your fork as this isnt the most active repository.

**Comment by chill117** [comment]
This session store is aimed at using MySQL directly without any intermediate cache. If your application requires higher performance session reads, I suggest to switch to [connect-redis](https://github.com/tj/connect-redis), which will use [redis](https://redis.io/) as its data store - with a focus on performance over correctness.
