### ISSUE TITLE
bump express-session version to support SameSite policy="None"

### ISSUE THREAD

**Issue by CheqAI** [chill117/express-mysql-session#104]
current express-session version (1.15.6) depends on cookie version 0.3.1, which doesnt support SameSite="None" policy. it seems like this issue is fixed in express-session 1.17.0, which depends on cookie 0.4.0.

Thank you very much for the support!

**Comment by CheqAI** [comment]
well, don't know how but magically my problem just resolved itself.
im able to receive response from my backend with sameSite="none" policy though it seems the current cookie version doesnt support it. 

anyway, im closing. thanks again!

**Comment by chill117** [comment]
The latest release of this module now includes the latest version of express-session so the "sameSite" cookie option should be fully supported.
