### ISSUE TITLE
Issue with setDefaultOptions

### ISSUE THREAD

**Issue by sudouser** [chill117/express-mysql-session#11]
express version 4.0

npm start generates the following
/node_modules/express-mysql-session/lib/index.js:31
        this.setDefaultOptions()
             ^

TypeError: Object #<Object> has no method 'setDefaultOptions'
    at module.exports (/home/ubuntu/d/myapp/node_modules/express-mysql-session/lib/index.js:31:7)
    at Object.<anonymous> (/home/ubuntu/d/myapp/app.js:22:25)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at Object.<anonymous> (/home/ubuntu/d/myapp/bin/www:7:11)
    at Module._compile (module.js:456:26)

**Comment by chill117** [comment]
Could you post the portion of your application code where you're instantiating the express-mysql-session store?

**Comment by sudouser** [comment]
Thanks for looking into it. Details below:

Here's my code snip:
var express = require('express');
var path = require('path');
var favicon = require('serve-favicon');
var logger = require('morgan');
var cookieParser = require('cookie-parser');
var expressSession = require('express-session');
var SessionStore = require('express-mysql-session');
var bodyParser = require('body-parser');
var routes = require('./routes/index');
var users = require('./routes/users');
var uuidGen = require('node-uuid');
var app = express();

var dbOptions = { <Initialized my db options here> }

var mysqlSessionStore = SessionStore(dbOptions);

app.use(bodyParser.json());
app.use(bodyParser.urlencoded({ extended: false }));
app.use(cookieParser());
app.use(expressSession(
        {
          key:'session_cookie_name',
          secret: 'somesecret',
          store: mysqlSessionStore,
          resave: true,
          saveUninitialized: true,
          expiration: 86400000,
          keepAlive: true,
          genid: function(req) {
              return uuidGen.v4() // use UUIDs for session IDs
          },
        }));
app.use(express.static(path.join(__dirname, 'public')));
app.use('/', routes);

-------- Below is my routes/app.js--------
router.get('/', function(req, res, next) {
  //res.cookie('TestCookie','TestData123', {signed: true, maxAge: 9999999999, httpOnly: true});
  if(!req.session.userName) {
        console.log('setting username');
        req.session.username = 'testuser';
  } else {
        console.log(req.session.username);
  }
  res.render('index', { title: 'Express' });
});

-------- My package.json--------
{
  "name": "myapp",
  "version": "0.0.0",
  "private": true,
  "scripts": {
    "start": "node ./bin/www"
  },
  "dependencies": {
    "body-parser": "~1.10.2",
    "cookie-parser": "~1.3.3",
    "debug": "~2.1.1",
    "express": "~4.11.1",
    "jade": "~1.9.1",
    "morgan": "~1.5.1",
    "serve-favicon": "~2.2.0",
    "express": "~4.11.2",
    "express-session": "~1.10.2",
    "node-uuid": "~1.4.2",
    "express-mysql-session": "~0.3.1"
  }
}

**Comment by chill117** [comment]
It appears you're missing the `new` operator when creating your session store instance.

```js
var mysqlSessionStore = SessionStore(dbOptions);
```

Should be changed to:
```js
var mysqlSessionStore = new SessionStore(dbOptions);
```

**Comment by sudouser** [comment]
What an embarrassing mistake. I'm sorry about the oversight and wasting your time. Thanks! .

**Comment by chill117** [comment]
No worries. Happens to everyone :)
