### ISSUE TITLE
Add documentation on how to use .get .all etc.

### ISSUE THREAD

**Issue by futurelucas4502** [chill117/express-mysql-session#111]
I am simply trying to use .get on a mysql store to get all the data however im not sure on how to use it can the docs be updated to include an example?

**Comment by chill117** [comment]
This module implements the API as described in the [express-session module](https://github.com/expressjs/session#session-store-implementation). So it's possible to get all the sessions from the store as follows:
```js
sessionStore.all(function(error, sessions) {
   // error or sessions array returned by callback. 
});
```

**Comment by futurelucas4502** [comment]
Ah okay thank you
