### ISSUE TITLE
Some things are missing in the documentation

### ISSUE THREAD

**Issue by mpgr04** [chill117/express-mysql-session#113]
I have been trying to figure out how to read data from the SessionStore for quite some time now. Since there are the methods .get and .all.

But I have no idea how to use them, because there is nothing written in the documentation.

It would be great if you could somehow clear this up

**Comment by chill117** [comment]
This module implements the API as described in the [express-session module](https://github.com/expressjs/session#session-store-implementation). So it's possible to get all the sessions from the store as follows:
```js
sessionStore.all(function(error, sessions) {
   // error or sessions array returned by callback. 
});
```

**Comment by mpgr04** [comment]
Oh, I get it now, I just tried it and it works. Thanks for the help!
