### ISSUE TITLE
Reuse an existing database connection

### ISSUE THREAD

**Issue by ilanbiala** [chill117/express-mysql-session#12]
It would be nice to use an already existing database connection instead of opening a new one and having 2 connections.

**Comment by chill117** [comment]
This is currently possible, but not documented. To re-use a database connection you would pass the connection object as the second argument when creating your session store, like this:

```js
var mysql = require('mysql')
var SessionStore = require('express-mysql-session')

var options = {
    host: 'localhost',
    port: 3306,
    user: 'db_user',
    password: 'password',
    database: 'db_name'
}

var connection = mysql.createConnection(options)
var sessionStore = new SessionStore(options, connection)
```

I will add this to the readme file so that others who want to do the same thing can find the information.

**Comment by ilanbiala** [comment]
Why do I need to pas in the options when I already have a connection?

**Comment by chill117** [comment]
You don't have to. You can do this instead, if you prefer:
```js
var mysql = require('mysql')
var SessionStore = require('express-mysql-session')

var options = {
    host: 'localhost',
    port: 3306,
    user: 'db_user',
    password: 'password',
    database: 'db_name'
}

var connection = mysql.createConnection(options)
var sessionStore = new SessionStore({}, connection)
```

**Comment by ilanbiala** [comment]
Why not just make it `new SessionStore(connection)` or `new SessionStore(options)` based on if the passed in variable has a connection-specific property to discern the two uses.

**Comment by chill117** [comment]
The SessionStore constructor takes 3 arguments:

```js
var SessionStore = module.exports = function(options, connection, cb) {
    // ..
}
```

Trying to discern the whether `options` is a connection object would likely introduce potential breakage if the mysql module changed in such a way to break the method used to do so. I don't feel like this use-case warrants such a risk.

**Comment by ilanbiala** [comment]
Perfect time to bump to 1.0.0 then with some pretty logical but breaking changes, no?

**Comment by ilanbiala** [comment]
Perfect time to bump to 1.0.0 then with some pretty logical but breaking changes, no?

**Comment by chill117** [comment]
Breakage in the sense that it would make this module less stable, as it would depend on the specific inner workings of the mysql module. Also it would add to the overall complexity of the code in the constructor. I try to keep things simple unless absolutely necessary.
