### ISSUE TITLE
Delete record from table when user log out?

### ISSUE THREAD

**Issue by BadPistol97** [chill117/express-mysql-session#122]
How to delete the record in the table when user log out? if I am supposed to do so.

**Comment by antefix-consulting** [comment]
I was wondering that the other day. If I read the source code correctly, expired session records are deleted automatically every fifteen minutes, so you do not need to delete them yourself.

**Comment by chill117** [comment]
In your application logic, you can delete the session of the active user when they logout. The express-session module adds the session ID to the request object of express as `req.session.id`. So in your logout route, you could delete the session row from your database using this session ID.

**Comment by chill117** [comment]
Closing this as it's likely been solved.
