### ISSUE TITLE
Incorrect string value

### ISSUE THREAD

**Issue by MadKilzz** [chill117/express-mysql-session#128]
When i make a session i get an error 
Error: ER_TRUNCATED_WRONG_VALUE_FOR_FIELD: Incorrect string value: '\xF0\x9F\xA6\x95",...' for column 'data' at row 1

i use the default options:
```js
var sessionStore = new MySQLStore({
    createDatabaseTable: true,
    schema: {
        tableName: 'sessions',
        columnNames: {
            session_id: 'session_id',
            expires: 'expires',
            data: 'data'
        }
    }
}, sql);
```

**Comment by chill117** [comment]
Looks like you're trying to save session data that includes characters not included in the utf8 encoding.

**Comment by MadKilzz** [comment]
> Looks like you're trying to save session data that includes characters not included in the utf8 encoding.

How can i fix it? i use express session with discord oauth2 (paspoort-discord) look liks there is not a characters what not is supported

**Comment by chill117** [comment]
Looks like the following stackoverflow post could help you:
https://stackoverflow.com/questions/20411440/incorrect-string-value-xf0-x9f-x8e-xb6-xf0-x9f-mysql
