### ISSUE TITLE
sessions table empty (using mysql2)

### ISSUE THREAD

**Issue by techvd** [chill117/express-mysql-session#134]
I'm using express-mysql-session with express-session and mysql2. The sessions table is created in my database but no session data gets stored. Within the app session works fine but only as long as the server is running, which makes me think somehow the session is going back to memory store but I'm not sure why. I enabled debugging and here's what I see during startup.

  express-mysql-session:log Creating session store +0ms
  express-mysql-session:log Creating sessions database table +1ms
  express-mysql-session:log Setting expiration interval to 900000ms +77ms
  express-mysql-session:log Clearing expiration interval +0ms

After that nothing gets logged again. Not even any errors. The code I'm using is very boiler-plate and nothing fancy or complicated. And like I said, if I delete the sessions table and restart the app, it gets created fine (with the right columns session_id, expires, data).

Any help further isolating the issue or troubleshooting is much appreciated. Please let me know if you need any more details

**Comment by schrudolf** [comment]
same problem

**Comment by chill117** [comment]
Please see the [with mysql2](https://github.com/chill117/express-mysql-session#with-mysql2) section in the readme.
