### ISSUE TITLE
Mysql2 dependency update needed

### ISSUE THREAD

**Issue by Nickk4** [chill117/express-mysql-session#151]
Mysql2 dependency has a critical security warning and needs to be updated to 3.9.4 or higher: https://github.com/advisories/GHSA-fpw7-j2hg-69v5

**Comment by pfiadDi** [comment]
Bump!

**Comment by chill117** [comment]
Updated mysql2 and a few dev dependencies to latest versions. Release version v3.0.1 now available.

> Bump!

I don't think bumping is needed only a few hours after the issue was posted ;)

**Comment by Nickk4** [comment]
Sorry, @chill117 , but there seems to be another critical security issue with mysql2: https://github.com/advisories/GHSA-8cp3-66vr-3r4c
Now it needs to be updated to 3.7.4 or higher...

**Comment by chill117** [comment]
Updated

**Comment by chriscant** [comment]
Hello @chill117 another security update for mysql2 is required: https://cve.mitre.org/cgi-bin/cvename.cgi?name=2024-21512
Can you please bump to 3.9.8 or later thanks
