### ISSUE TITLE
mysql2 dependency outdated?

### ISSUE THREAD

**Issue by gom59** [chill117/express-mysql-session#153]
Running npm audit gives this:

`
mysql2  <3.9.8
Severity: high
mysql2 vulnerable to Prototype Pollution - https://github.com/advisories/GHSA-pmh2-wpjm-fj45
fix available via "npm audit fix --force"
Will install express-mysql-session@2.1.8, which is a breaking change
node_modules/express-mysql-session/node_modules/mysql2
  express-mysql-session  >=3.0.0
  Depends on vulnerable versions of mysql2
  node_modules/express-mysql-session

2 high severity vulnerabilities

To address all issues (including breaking changes), run:
  npm audit fix --force
`
This package effectively calls for mysql2 rev 3.9.7

Can we update this dependency?

**Comment by mark-pav** [comment]
Yes please

**Comment by pfiadDi** [comment]
Hi, would be really great if that could be done! :) thank you!!

**Comment by Kareszrk** [comment]
I have already resolved the issue, but still not merged idk why.
https://github.com/chill117/express-mysql-session/pull/152

If you could help us get this pull request through would be thanked

**Comment by chill117** [comment]
Thanks for bringing this to my attention. Upgraded to latest mysql2 and a new release of this module is now available.
