### ISSUE TITLE
Allow ability to choose database table name

### ISSUE THREAD

**Issue by chaudhry-junaid** [chill117/express-mysql-session#16]
It would be nice to be able to specify the name of the sessions table to create as an option to the session store. Possible use case is consistent naming of database tables. Thanks.

**Comment by chill117** [comment]
There is a [pending pull request](https://github.com/chill117/express-mysql-session/pull/15) for this. Waiting for some fixes in it as well as added tests.

**Comment by davidmcl** [comment]
+1 - really would be good to have the table name parameter.

It would appear that the original pull request submitter is not following up on this - more than a month later. 

Any chance that this will be completed?

Thanks.

**Comment by chill117** [comment]
Yes, it appears that person has abandoned their plans to finish up the pull request. There have been several people at least who have wanted this, so I'll just go ahead and implement it myself the next chance I get. I think I may have some time to do this over the weekend.

**Comment by chill117** [comment]
All set. This feature is now included in version 0.4.0.

**Comment by davidmcl** [comment]
Excellent - thanks much.

David

**Comment by chaudhry-junaid** [comment]
Thanks! :+1:
