### ISSUE TITLE
SessionStore does not delete expired sessions from the DB table

### ISSUE THREAD

**Issue by dkung** [chill117/express-mysql-session#17]
I believe it's due to the fact that setExpirationInterval() is not being called anywhere in the code so nothing to initiate the setInterval callback?

**Comment by chill117** [comment]
Do you by chance have the `createDatabaseTable` option set to `false`? I took a look at the code. It appears that the `setExpirationInterval()` is called, but within the `createDatabaseTable()` method. So if you have the `createDatabaseTable` option set to `false`, it won't ever be called as you said. When I get a bit of time I will correct this issue, but in the mean time you can call the `setExpirationInterval` method manually on your session store object in your code.

**Comment by dkung** [comment]
Yes you are right.  I set createDatabaseTable to false. For security reason

**Comment by chill117** [comment]
All set. Version 0.3.3 includes the fix for this issue.
