### ISSUE TITLE
MySQL is not reconnecting gracefully, causing store to fail with "Cannot enqueue Query after fatal error"

### ISSUE THREAD

**Issue by Domiii** [chill117/express-mysql-session#18]
Currently, `express-mysql-session` cannot properly handle DB connection failures. After a connection has been terminated, the store will always fail with:

    Error during request (500): Error: Cannot enqueue Query after fatal error.
    at Protocol._validateEnqueue (MY_CODE\node_modules\express-mysql-session\node_modules\mysql-connection-manager\node_modules\mysql\lib\protocol\Protocol.js:193:16)
    at Protocol._enqueue (MY_CODE\node_modules\express-mysql-session\node_modules\mysql-connection-manager\node_modules\mysql\lib\protocol\Protocol.js:129:13)
    at Connection.query (MY_CODE\node_modules\express-mysql-session\node_modules\mysql-connection-manager\node_modules\mysql\lib\Connection.js:185:25)
    at SessionStore.get (MY_CODE\node_modules\express-mysql-session\lib\index.js:127:18)
    at Layer.session [as handle] (MY_CODE\node_modules\express-session\index.js:404:11)

That is actually not a bug but intended behavior. I quote [`node-mysql`'s official documentation](https://github.com/felixge/node-mysql/#server-disconnects):

> Re-connecting a connection is done by establishing a new connection. Once terminated, an existing connection object cannot be re-connected by design.

However, [gracefully handling connection failures are still an open issue](https://github.com/felixge/node-mysql/issues/832).

In [version 0.0.12](https://github.com/chill117/express-mysql-session/tree/cf1962650ced7d7ebcd95cce97e24a9179dc0068), `express-mysql-session` had a `reconnect()` method. I would suggest to 1) either re-introduce that behavior or 2) provide some other way of handling DB connection problems.

For reference, I am sharing the code that handled connection errors in `0.0.12`, based on [this suggestion](https://github.com/felixge/node-mysql/issues/832/#issuecomment-44478560) (it works very well, and I will now go back to `0.0.12` for that reason):

    // remember if connection already failed (since mysql lib might raise errors more than once)
    var fataled = false;
    var reconnectTimer = null;

    // create store
    var store = ...;

    // use MySQL connection error handler hack
    // see: https://github.com/felixge/node-mysql/issues/832/#issuecomment-44478560
    var del = store.connection._protocol._delegateError;
    store.connection._protocol._delegateError = function(err, sequence){
        if (fataled) return;        // ignore silently

        if (err.fatal) {
            // fatal error -> Gotta re-connect!
            fataled = true; 
            var reconnectDelay = dbOptions.reconnectDelay || 5;

            console.error('mysql fatal error: ' + err.stack);
            console.warn('Connection to database lost. Reconnecting in ' + reconnectDelay + 's...');

            // re-connect after delay
            reconnectTimer = setTimeout(function() {
                fataled = false;
                reconnectTimer = null;
                store.reconnect();
            }, reconnectDelay * 1000);
        }
        else {
            // propagate error
            return del.call(store.connection._protocol, err, sequence);
        }
    };

    // use `store`...
    var session = { ... store: store, ... };

**Comment by chill117** [comment]
The reason the reconnect method (and other related methods) were removed from `express-mysql-session` was because that behavior is now handled by [mysql-connection-manager](https://github.com/chill117/mysql-connection-manager).

Hopefully this weekend I will have some time to look into this in more detail.

**Comment by Domiii** [comment]
Ok. FYI: Even if the manager re-connects, `express-mysql-session` is never getting the new connection from the manager.

It appears, the simplest solution is to just use a [connection pool](https://github.com/felixge/node-mysql/#pooling-connections) and call `getConnection` for each query. This way, you also do not have to implement re-sending of previously failed queries after re-connect.

**Comment by chill117** [comment]
> It appears, the simplest solution is to just use a connection pool and call getConnection for each query. This way, you also do not have to implement re-sending of previously failed queries after re-connect.

You can use connection pooling by passing the following option when instantiating the session store:
```js
{
    useConnectionPooling: true
}
```

**Comment by Domiii** [comment]
Yeah, that's a fine option! However, you are currently caching the `connection` of the pool. As I said: You need to use [getConnection](https://github.com/felixge/node-mysql/#pooling-connections) instead to make it work.

**Comment by chill117** [comment]
Ah yes. You are correct. I will fix this over the weekend.

**Comment by Domiii** [comment]
Hum... Interesting! So renaming `connection` to `queryInterface` and then either assign the connection or pool to it initially should fix everything.

**Comment by chill117** [comment]
No. The `connection` object from [mysql-connection-manager](https://github.com/chill117/mysql-connection-manager) is the connection pool object from [node-mysql](https://github.com/felixge/node-mysql) if you the following option to the `express-mysql-session` store:
```js
{
    useConnectionPooling: true
}
```

No modification is required to make it work even now.

**Comment by Domiii** [comment]
Ok... Maybe the naming should be adjusted correspondingly?
