### ISSUE TITLE
Always Creates DB Table with name 'sessions'

### ISSUE THREAD

**Issue by lukeavsec** [chill117/express-mysql-session#19]
The below code always creates a sessions database table with name 'sessions' instead of my defined 'httpSessions'

My dive into the source code suggests that if `options.createDatabaseTable == true` then index.js pulls its sql code from schema.sql in the module root folder. And that always uses 'sessions' to name the database table.

Perhaps I misunderstand the documentation but at the very least this is counter intuitive.

    var MysqlSessionStore = require('express-mysql-session');

    var sessionStore = new MysqlSessionStore({
        host: mysql_host,
        port: mysql_port,
        user: mysql_user, 
        password: mysql_password,
        database: mysql_database,
        schema: {
	        tableName: 'httpSessions'
        }
    });

I love this library - just trying to improve it. Thanks!

**Comment by chill117** [comment]
Right now you would have to specify not only the `tableName` but also the `columnNames`, like this:
```js
	schema: {
		tableName: 'httpSessions',
		columnNames: {
			session_id: 'session_id',
			expires: 'expires',
			data: 'data'
		}
	}
```

If you leave out the `columnNames`, an error will be thrown:
```
 Uncaught TypeError: Cannot read property 'session_id' of undefined
```

I just checked, and there is only one database table created when using the `schema` option. Are you sure the `sessions` table wasn't already there before? Are you getting any other errors?
