### ISSUE TITLE
Set/Get race condition

### ISSUE THREAD

**Issue by SergeKornilov** [chill117/express-mysql-session#21]
In case when "express-mysql-session" uses connection pooling then sometimes it leads to race condition regardless of setting save option for "express-session" module (false or true has no matter).
It can be obviously visible when we use extra debug calls like following in express-mysql-session/lib/index.js:

For "Setting session, sql:" here:

```javascript
SessionStore.prototype.set = function(session_id, data, cb) {
    ...
	this.connection.query(sql, params, function(error) {
+        debug_log('Setting session, sql: %s, params: %j', sql, params);
```

For "Getting session, sql: " and "Getting session, session:" here:

```javascript
SessionStore.prototype.get = function(session_id, cb) {
    ...
	this.connection.query(sql, params, function(error, rows) {
+        debug_log('Getting session, sql: %s, params: %j', sql, params);
		if (error) {
			return cb(error, null);
		}
		var session = !!rows[0] ? JSON.parse(rows[0].data) : null;
+        debug_log('Getting session, session: %j', session);
```

So I decided to switch off connection pooling but anyways, how can I be fully confident in lack of such race condition situations?

**Comment by chill117** [comment]
I am not sure what the problem is? Race conditions should be handled in the application code. This module is simply a MySQL storage engine for the `express-session` module.
