### ISSUE TITLE
Cant connect to a database on different server

### ISSUE THREAD

**Issue by MegazeroMZ** [chill117/express-mysql-session#22]
Hi, I'm using sails js along with your express-mysql-session, and this is how my session.js look like:

var MySQLSessionStore = require('express-mysql-session');

    var store_options = {
    host: 'localhost',
    port: 3306,
    user: 'usrName',
    password: 'xxxxxxxxxxx',
    database: 'databaseA',
    createDatabaseTable: true,
    schema: {
            tableName: 'sessions',
            columnNames: {
                session_id: 'session_id',
                expires: 'expires',
                data: 'data'
            }
        }
    }
    
module.exports.session = {
store: new MySQLSessionStore(store_options)
};

And it work fine for me. I was able to create a session and save it data to my local database.

The problem come when I trying to use a database from a remote server instead of my local host, i change the option to 

 host: 'http://xxx.xxx.xxx.xxx/',
    port: 3306,
    user: 'usrName',
    password: 'xxxxxxxxxxx',
    database: 'databaseA',

and when I sails lift and enter the website I got this error:

"Error occurred in session middleware :: 'Error: Cannot enqueue Query after fatal error.\n at Protocol._validateEnqueue (C:\\Sails\\Rank FE\\Rank\\node_modules\\express-mysql-session\\node_modules\\mysql-connection-manager\\node_modules\\mysql\\lib\\protocol\\Protocol.js:193:16)\n at Protocol._enqueue (C:\\Sails\\Rank FE\\Rank\\node_modules\\express-mysql-session\\node_modules\\mysql-connection-manager\\node_modules\\mysql\\lib\\protocol\\Protocol.js:129:13)\n at Connection.query (C:\\Sails\\Rank FE\\Rank\\node_modules\\express-mysql-session\\node_modules\\mysql-connection-manager\\node_modules\\mysql\\lib\\Connection.js:185:25)\n at SessionStore.get (C:\\Sails\\Rank FE\\Rank\\node_modules\\express-mysql-session\\lib\\index.js:151:18)\n at session (C:\\Sails\\Rank FE\\Rank\\node_modules\\sails\\node_modules\\express\\node_modules\\connect\\node_modules\\express-session\\index.js:324:11)\n at Object._.defaults.session [as handle] (C:\\Sails\\Rank FE\\Rank\\node_modules\\sails\\lib\\hooks\\http\\middleware\\defaults.js:50:11)\n at next (C:\\Sails\\Rank FE\\Rank\\node_modules\\sails\\node_modules\\express\\node_modules\\connect\\lib\\proto.js:169:15)\n at Object.cookieParser [as handle] (C:\\Sails\\Rank FE\\Rank\\node_modules\\sails\\node_modules\\express\\node_modules\\connect\\node_modules\\cookie-parser\\index.js:48:5)\n at next (C:\\Sails\\Rank FE\\Rank\\node_modules\\sails\\node_modules\\express\\node_modules\\connect\\lib\\proto.js:169:15)\n at Object.startRequestTimer [as handle] (C:\\Sails\\Rank FE\\Rank\\node_modules\\sails\\lib\\hooks\\http\\middleware\\defaults.js:72:7)\n at next (C:\\Sails\\Rank FE\\Rank\\node_modules\\sails\\node_modules\\express\\node_modules\\connect\\lib\\proto.js:169:15)\n at Object.expressInit [as handle] (C:\\Sails\\Rank FE\\Rank\\node_modules\\sails\\node_modules\\express\\lib\\middleware.js:30:5)\n at next (C:\\Sails\\Rank FE\\Rank\\node_modules\\sails\\node_modules\\express\\node_modules\\connect\\lib\\proto.js:169:15)\n at Object.query [as handle] (C:\\Sails\\Rank FE\\Rank\\node_modules\\sails\\node_modules\\express\\node_modules\\connect\\lib\\middleware\\query.js:45:5)\n at next (C:\\Sails\\Rank FE\\Rank\\node_modules\\sails\\node_modules\\express\\node_modules\\connect\\lib\\proto.js:169:15)\n at Function.app.handle (C:\\Sails\\Rank FE\\Rank\\node_modules\\sails\\node_modules\\express\\node_modules\\connect\\lib\\proto.js:177:3)'"

And if I remove the http part from the host so the option is host: 'xxx.xxx.xxx.xxx' then I got this error:

Error occurred in session middleware :: 'Error: connect ETIMEDOUT\n at Connection._handleConnectTimeout (C:\\Sails\\Rank FE\\Rank\\node_modules\\express-mysql-session\\node_modules\\mysql-connection-manager\\node_modules\\mysql\\lib\\Connection.js:346:13)\n at Socket.g (events.js:199:16)\n at Socket.emit (events.js:104:17)\n at Socket._onTimeout (net.js:348:8)\n at _makeTimerTimeout (timers.js:467:11)\n at Timer.unrefTimeout (timers.js:531:5)\n --------------------\n at Protocol._enqueue (C:\\Sails\\Rank FE\\Rank\\node_modules\\express-mysql-session\\node_modules\\mysql-connection-manager\\node_modules\\mysql\\lib\\protocol\\Protocol.js:135:48)\n at Protocol.handshake (C:\\Sails\\Rank FE\\Rank\\node_modules\\express-mysql-session\\node_modules\\mysql-connection-manager\\node_modules\\mysql\\lib\\protocol\\Protocol.js:52:41)\n at Connection.connect (C:\\Sails\\Rank FE\\Rank\\node_modules\\express-mysql-session\\node_modules\\mysql-connection-manager\\node_modules\\mysql\\lib\\Connection.js:109:18)\n at MySQLConnectionManager.createConnection (C:\\Sails\\Rank FE\\Rank\\node_modules\\express-mysql-session\\node_modules\\mysql-connection-manager\\lib\\index.js:66:13)\n at MySQLConnectionManager.connect (C:\\Sails\\Rank FE\\Rank\\node_modules\\express-mysql-session\\node_modules\\mysql-connection-manager\\lib\\index.js:56:8)\n at MySQLConnectionManager.reconnect (C:\\Sails\\Rank FE\\Rank\\node_modules\\express-mysql-session\\node_modules\\mysql-connection-manager\\lib\\index.js:160:7)\n at null._onTimeout (C:\\Sails\\Rank FE\\Rank\\node_modules\\express-mysql-session\\node_modules\\mysql-connection-manager\\lib\\index.js:148:8)\n at Timer.listOnTimeout (timers.js:110:15)'

Any idea how I might fix this?

**Comment by chill117** [comment]
The `host` option should be the IP address of the remote server (no http, no slashes). Also, are you sure you've configured the remote MySQL instance to accept remote connections? Try command from your terminal:
```
mysql --user=USER --password=PASSWORD --host=HOST --port=PORT
```
Be sure you replace all the uppercase strings with the real values.

**Comment by MegazeroMZ** [comment]
Oh I forgot to configure the mysql instance to accept remote connections. Thanks
