### ISSUE TITLE
Support for mysql:// uri's?

### ISSUE THREAD

**Issue by vidia** [chill117/express-mysql-session#23]
I am using the sql uri for my other database connections, can I not use it for this too or do I need to make it into a set of keys for the options.

**Comment by chill117** [comment]
[node-mysql] is used to establish MySQL connections. You should only have to provide the following connection information for it to work:
```js
var options = {
    host: 'localhost',
    port: 3306,
    user: 'session_test',
    password: 'password',
    database: 'session_test'
};

var sessionStore = new SessionStore(options);
```

You do **not** need to specify the protocol (`mysql:`, `https:`) in the `host` option.
