### ISSUE TITLE
Non-session Cookies

### ISSUE THREAD

**Issue by AdamYoungberg** [chill117/express-mysql-session#25]
Perhaps I am missing something simple here, if so, please gently point me in the right direction.

I've noticed when I add a session expiration time, the cookie converts from a browser-based session cookie to a normal client-cookie.  I'd would prefer to keep the cookies as pure browser-based session cookies but still have the option for them to be automatically cleared from the DB at an interval.

**Comment by chill117** [comment]
I think you're a bit confused about cookies. Cookies are simply little files containing text that are stored by your browser. Their contents are sent the server in a request for a web page (if the domain name is a match). In the case of session stores (in express/connect), the session cookies used are storing a session identifier (ID) which is used to identify the request and associate it with an existing session (arbitrary data on the server). This is how the server can remember things about a user.

**Comment by AdamYoungberg** [comment]
I agree with your explanation with one critical difference.  My understanding is that session cookies are stored in memory by the browser and do not persist beyond its open state. Non-session cookies are stored in files on the file system. While either could be used, browser session cookies are more secure as they are not accessible on disk and are generally preferred for this reason.

I've been able to verify the above in Chrome. When no expiration is set, the cookie is marked with the session cookie flag. When an expiration date is provided, it is not, and I can locate it on the file system.  I would like to have cookies behave as proper browser session cookies but where they will clear from the database at a defined interval. 

If this is unclear or if I am still misunderstanding something, I apologize. I'll do more research as needed, and if I devise a solution after that which merits your attention, I'll share it. Thank you for your response.

**Comment by chill117** [comment]
A better reference might be the following:
https://en.wikipedia.org/wiki/HTTP_cookie

I think I understand what you're asking for now. You need to look at the [express-session](https://github.com/expressjs/session) module. Specifically the `maxAge` option that you pass in when setting up your session middleware:
```js
app.use(session({
    key: 'session_cookie_name',
    secret: 'session_cookie_secret',
    store: sessionStore,
    resave: true,
    saveUninitialized: true,
    maxAge: null// This will make sure that no expire date is set for the cookie, making it a "session-only cookie"
}));
```

A stackoverflow discussion that might be useful for you as well:
http://stackoverflow.com/questions/4371178/session-only-cookie-for-express-js
