### ISSUE TITLE
multi-tenant session store?

### ISSUE THREAD

**Issue by krisdahl** [chill117/express-mysql-session#27]
I'm wondering if anyone has tackled doing a multi-tenant system with express-mysql-session?

Our system currently has a mysql database for each tenant.  Thoughts?

**Comment by chill117** [comment]
I think that could work. You can create a separate session store for each tenant/database. Just provide the different database connection (or config) when instantiating each session store.

**Comment by krisdahl** [comment]
Cool.  Thanks.  I may take a stab at it, and I'm also considering just having a federated/global session store and managing the multi-tenancy another way.

I don't think that creating separate session store will work for us--we do the multi-tenant partitioning on every request, rather than on initializing server.

**Comment by chill117** [comment]
> .. I'm also considering just having a federated/global session store and managing the multi-tenancy another way.

You may want to consider adding another couple fields to the sessions database table (`user_id` and `tenant_id`). That's how I've managed multi-tenancy in the past.
