### ISSUE TITLE
Failed to create sessions database table should be traced using debug_error

### ISSUE THREAD

**Issue by cgalibern** [chill117/express-mysql-session#29]
instead of depending on self.option.debug value

**Comment by chill117** [comment]
I agree. There are other places as well that should be calling `debug_error()` without needing the `debug` option to be set. Can you create a PR with the fixes?

**Comment by cgalibern** [comment]
@chill117, this fix is here to get correct error message when DEBUG='express-mysql-session:*' is set.

Thanks
