### ISSUE TITLE
Is it possible to have a callback function when a user is timed out ?

### ISSUE THREAD

**Issue by bbung24** [chill117/express-mysql-session#31]
I am trying to log every session login/logout/time-out. I can do login and logout from server api, but I also want to do logging for time-out. Is there a way to do it right now using this module?

**Comment by chill117** [comment]
What do you mean by time-out?

**Comment by bbung24** [comment]
I meant expiration of valid session !

**Comment by chill117** [comment]
This module isn't meant to be interacted with in the way you are describing. Sessions are cleared periodically by running a delete query against the MySQL database. There's no callback for when any specific session is deleted or expired. I suggest looking to another part of your application code to do this.

**Comment by bbung24** [comment]
I see. That makes sense. I will try to look at other ways to do this ! Thanks for quick reply.
