### ISSUE TITLE
Connect using socketpath and or db uri's?

### ISSUE THREAD

**Issue by aybmab** [chill117/express-mysql-session#32]
Is there a way to connect using a socket path or a db url?

Thanks in advance!!

**Comment by chill117** [comment]
You can create a MySQL connection using the [node-mysql](https://github.com/felixge/node-mysql#connection-options) module and then pass the connection object when creating the session store:
```js
var mysql = require('mysql');
var SessionStore = require('express-mysql-session');
var connection = mysql.createConnection('mysql://user:pass@host/db?debug=true&charset=BIG5_CHINESE_CI&timezone=-0700');
var options = {};
var sessionStore = new SessionStore(options, connection);
```

**Comment by aybmab** [comment]
Thanks! Sorry, I just read through the readme more carefully.
