### ISSUE TITLE
__prototype__ functions removal issue

### ISSUE THREAD

**Issue by Kopfy** [chill117/express-mysql-session#33]
I found that when some middleware extends the Session object prototype with e.g. some additional functions the _express-mysql-session_ store somehow removes such functions...

In particular... I'm trying to use the _easy-session_ module (https://www.npmjs.com/package/easy-session) in combination with this session store....

I found that when I use _easy-session_ with default session store (_memory-store_) everything works normally, however, when I use _express-mysql-session_, it deletes the Session.prototype functions added by the _easy-session_...

`req.session.__proto__` functions available (when using _memory-store_ - correct):
```
touch,resetMaxAge,save,reload,destroy,regenerate,login,logout,setLastRequest,isGuest,isLoggedIn,isFresh,setRole,getRole,hasRole,hasNotRole
```

`req.session.__proto__` functions available (when using _express-mysql-session_ - missing functions):
```
touch,resetMaxAge,save,reload,destroy,regenerate
```

How to repair this?

**Comment by chill117** [comment]
This module extends from the [express-session]() module's prototype:
```js
var session = require('express-session');
// ..
SessionStore.prototype = new session.Store();
SessionStore.prototype.constructor = SessionStore;
```

I will have to dig into why the memory store works to see if it's something that can be imported to this module. If you come up with a solution in the mean time, please let me know.
