### ISSUE TITLE
PROTOCOL_ENQUEUE_AFTER_FATAL_ERROR, I use pooling

### ISSUE THREAD

**Issue by b3nk3** [chill117/express-mysql-session#34]
I have the below code working just fine, but after a rough 12-16 hours period it shuts down and I get this message:

`PROTOCOL_ENQUEUE_AFTER_FATAL_ERROR`

Could you point out what did I do wrong? I don't have a great knowledge about this stuff, followed a tutorial, however the connection is not stable.

```
var express = require("express");
var mysql   = require("mysql");
var bodyParser  = require("body-parser"); 
var md5 = require('md5');
var rest = require("./REST.js");
var app  = express();
var currentDateAndTime = new Date();

function REST(){
    var self = this;
    self.connectMysql();
};

REST.prototype.connectMysql = function() {
    var self = this;
    var pool      =    mysql.createPool({
        connectionLimit : 100,
        host : "localhost",
            user : "",
            password : "",
            database : "",
        debug    :  false
    });
    pool.getConnection(function(err,connection){
        if(err) {
          self.stop(err);
        } else {
          self.configureExpress(connection);
        }
    });
}

REST.prototype.configureExpress = function(connection) {
      var self = this;
      app.use(bodyParser.urlencoded({ extended: true }));
      app.use(bodyParser.json());
      var router = express.Router();
      app.use('/api', router);
      var rest_router = new rest(router,connection,md5);
      self.startServer();
}

REST.prototype.startServer = function() {
      app.listen(3000,function(){
          console.log(currentDateAndTime + " All right ! I am alive at Port 3000.");
      });
}

REST.prototype.stop = function(err) {
    console.log(currentDateAndTime + " ISSUE WITH MYSQL n" + err);
    process.exit(1);
}

new REST();
```

**Comment by chill117** [comment]
It doesn't look like you're using this module?

Just from looking at your code, it looks like the tutorial was quite old. What are you trying to do with your application?

**Comment by b3nk3** [comment]
Hello, it is to connect to a db that serves an api. The queries and the upstart script is intact. but after a certain amount of time it drops the db connection.

How could I improve this code to make the connection stable? Or could you point me to the right resources?

**Comment by chill117** [comment]
Maybe you could try using [restify](https://github.com/restify/node-restify).

**Comment by b3nk3** [comment]
The REST part of it is working, it only struggles wtih maintaining the mysql connection or reestablishing it.

**Comment by chill117** [comment]
Did you look at the documentation for the [node-mysql](https://github.com/felixge/node-mysql#pooling-connections) module?

**Comment by b3nk3** [comment]
Yes, and found an issue at their site with a similar title as mine, ad in the comments they have diverted the person to you guys. that is how I got here.

Anyway if this is not the right place, that is a step forward. Slowly but steadily the problem is in a small circle now :D

**Comment by RobbieLePommie** [comment]
The issue you are experiencing will be "This Server Has Gone Away": http://dev.mysql.com/doc/refman/5.7/en/gone-away.html 

You can adjust the "gone away" timeout (read the docs above) but this only delays the issue.

What happens in node is that the pool returns what it thinks is a valid connection, but isn't. There needs to be a way to telling the connection pool "this connection is dead, drop it from your list, give me another one" but I can't see one in the docs, other than dropping the entire pool.

There is the config option "removeNodeErrorCount" https://github.com/felixge/node-mysql#poolcluster-option which you an actually see working: after 5 query attempts in my code it automatically got a new connection. So you could drop this to 1 (as actually suggested in the docs) or work a loop around your queries to trap the errors and retry query if it's the "gone away" message you experience. (https://github.com/felixge/node-mysql#error-handling)

**Comment by RobbieLePommie** [comment]
Edit: found the call in docs.

What you need is "connection.destroy()" for the pool. So sequence is
 - do query,
 - if it fails with the above error,
 -  - call "connection.destroy()",
 -  - grab a new connection from the pool, and
 -  - redo the query. 

But probably want to trap this to make sure you don't infinitely loop.

Would be nice if this was handled by the class - it only handles if a "ping" fails ("When a previous connection is retrieved from the pool, a ping packet is sent to the server to check if the connection is still good.") but the server will respond to a ping.

**Comment by b3nk3** [comment]
Hello, in the meantime i found a similar solution. I will try when I have time. Thanks for your efforts.

**Comment by chill117** [comment]
I am closing this as it's out-of-scope for this project.
