### ISSUE TITLE
How to access session data?

### ISSUE THREAD

**Issue by amanuel2** [chill117/express-mysql-session#35]
Forgot to tell us how we retrieve the data from cookie session...

**Comment by chill117** [comment]
Could you explain a bit more what you mean by that, please?

**Comment by amanuel2** [comment]
Ok you told us we can store a session variable.. but how do we retrieve the session variable... (and i didnt mean to say cookie lol)

**Comment by chill117** [comment]
This module is just a MySQL storage engine for the [express-session](
https://github.com/expressjs/session) module. You can read about how to access session data for a request [here](https://github.com/expressjs/session#reqsession).
