### ISSUE TITLE
doc version confusion 

### ISSUE THREAD

**Issue by GingerBear** [chill117/express-mysql-session#36]
I try to npm install and it installed `0.4.4`. but the doc on https://www.npmjs.com/package/express-mysql-session on actually for `v1.0.0-rc.0`. This might be a minor thing but it took me hours to figure out. It would be nice if a notice could be put in readme to reduce possible confusion.

**Comment by chill117** [comment]
I've added a note near the top of the documentation for anyone still using an old version of this module.

I am not able to reproduce your specific issue though. I've tried installing this module with the following variations:
* Node 4 (latest) with npm 2.x
* Node 5 (latest) with npm 3.x
* Both of the above with and without the `--production` flag

**Comment by GingerBear** [comment]
turns out I was using node `4.2.0` and it installed `0.4.4`. When I updated node to latest `4.4.0`, it installs `1.0.0-rc.0`

**Comment by chill117** [comment]
Confirmed. I just tried installing this module with node v4.2.0 (and npm v2.14.7) and it did install version 0.4.4 of this module. Very strange.. Could be a bug with the way that version of npm resolves package version numbers from the npm repository.
