### ISSUE TITLE
Error: Cannot enqueue Query after fatal error.

### ISSUE THREAD

**Issue by aybmab** [chill117/express-mysql-session#38]
Delete please.

**Comment by chill117** [comment]
GitHub doesn't allow deleting issues. Best we can do is close them.

**Comment by firasdib** [comment]
How did you solve this?

**Comment by chill117** [comment]
I believe they solved the issue by using a [connection pool](https://github.com/felixge/node-mysql#pooling-connections). You can pass the connection pool object to `express-mysql-session` like this:
```js
var mysql = require('mysql');
var session = require('express-session');
var MySQLStore = require('express-mysql-session')(session);

var options = {
    host: 'localhost',
    port: 3306,
    user: 'db_user',
    password: 'password',
    database: 'db_name'
};

var connection = mysql.createPool(options);
var sessionStore = new MySQLStore({}/* session store options */, connection);
```

**Comment by aybmab** [comment]
Apologies for deleting the content of the post!

The connection pool did solve the problem. I also recently stopped using mysql since it happened to be less stable when pushing to heroku than postgres.

**Comment by firasdib** [comment]
Thank you!
