### ISSUE TITLE
Reconnect on error?

### ISSUE THREAD

**Issue by TomMettam** [chill117/express-mysql-session#40]
If the MySQL server goes away, it appears that express-mysql-session doesn't attempt to reconnect automatically.

server-0 Error: Cannot enqueue Query after fatal error.
server-0     at Protocol._validateEnqueue (/home/ubuntu/server/node_modules/express-mysql-session/node_modules/mysql-connection-manager/node_modules/mysql/lib/protocol/Protocol.js:199:16)
server-0     at Protocol._enqueue (/home/ubuntu/server/node_modules/express-mysql-session/node_modules/mysql-connection-manager/node_modules/mysql/lib/protocol/Protocol.js:135:13)
server-0     at Connection.query (/home/ubuntu/server/node_modules/express-mysql-session/node_modules/mysql-connection-manager/node_modules/mysql/lib/Connection.js:201:25)
server-0     at MySQLStore.get (/home/ubuntu/server/node_modules/express-mysql-session/lib/index.js:135:19)

**Comment by chill117** [comment]
Can you post the code snippet where you are using this module?
