### ISSUE TITLE
Can I use events ?

### ISSUE THREAD

**Issue by Ezekiah** [chill117/express-mysql-session#45]
Hello,
My plan is to call some extra code when the destroy function is called by me or automatically by your program(when you check expiry), how can I do that ?

Example : 
sessionStore.on('destroy', function(){
...
})

Is it possible ?

**Comment by chill117** [comment]
This is not currently possible. The session store is an [EventEmitter](https://nodejs.org/api/events.html), but there aren't any events emitted for anything other than errors.

**Comment by Ezekiah** [comment]
How can I extra function when the program delete expired session ?

**Comment by chill117** [comment]
> How can I call [a] function when the program deletes expired sessions?

This is not currently possible. But you are not the first person to ask for this. It should be easy enough to trigger an event when expired sessions have been cleared - but this would have to be done internally.

May I ask why you need to be able to run a function immediately after expired sessions have been deleted?

**Comment by Ezekiah** [comment]
Because I need to update another table(security table) where the session id, ip, user agent of all my users, so when the sessionid is expired it should not be in my other table anymore.

**Comment by chill117** [comment]
That sounds like a perfect use-case for [MySQL's ON DELETE CASCADE](http://www.mysqltutorial.org/mysql-on-delete-cascade/) feature. You can add a foreign key to your `security` table on the `sessionid` column which references the `session_id` column in the `sessions`. Then you just add `ON DELETE CASCADE` to the `sessions` table.

**Comment by Ezekiah** [comment]
Yeah you are totally right :+1: 
Thanks.

**Comment by chill117** [comment]
You're welcome :)

**Comment by Ezekiah** [comment]
However now I would like to send a websocket when a session is expired so that I disconnect in real time the user, I'm trying to read the mysql bin/log with the npm package zongji to catch changes on my DB but It would be easiere to have the events, can you add this functionality ? Is it long to develop ?

**Comment by chill117** [comment]
I'm not sure it's a use-case I want to support. It seems very much an edge case that would be better solved with some re-designing in the application layer.

**Comment by Ezekiah** [comment]
Can you help me to implement that ?
I forked and tried to add emit('destroy') but it's not working.
https://github.com/Ezekiah/express-mysql-session/commit/c9aa3e1da27d622b2b2eebaac05df6970cf7a240

**Comment by chill117** [comment]
You must change the following:
```js
		this.connection.query(sql, params, function(error) {

			if (error) {
				debug_error('Failed to insert session data.');
				debug_error(error);
				return cb && cb(error);
			}
			this.emit('setting');
			cb && cb();
			
		});
```

To this:
```js
		this.connection.query(sql, params, function(error) {

			if (error) {
				debug_error('Failed to insert session data.');
				debug_error(error);
				return cb && cb(error);
			}
			this.emit('setting');
			cb && cb();
			
		}.bind(this));
```

**Comment by Ezekiah** [comment]
I did like this :

var self = this;
		this.connection.query(sql, params, function(error) {

			if (error) {
				debug_error('Failed to insert session data.');
				debug_error(error);
				return cb && cb(error);
			}
			self.emit('setting');
			cb && cb();

		});

Its working, thanks ;)
