### ISSUE TITLE
Type error calling getTime against cookie expiry date

### ISSUE THREAD

**Issue by rgee0** [chill117/express-mysql-session#46]
```
session = require('express-session'),
MySQLStore = require('express-mysql-session')(session);

sessionStore = new MySQLStore({}, con);

app = require('sockpress').init({
        key: '...',
        store: sessionStore,
        secret: '...',
        resave: true,
        saveUninitialized: true,
        cookie: {expires: new Date("2105")}
});
```

Trips up with a type error on line 157 node_modules/express-mysql-session/lib/index.js as getTime cannot function against what is a string

Changing:

`expires = data.cookie.expires;`

To:

`expires = new Date(data.cookie.expires);`

resolves the issue but it feels like `data.cookies.expires` should already be a date object.

**Comment by chill117** [comment]
I am not entirely sure where `data.cookies.expires` comes from. But I think a good solution is what you did - wrap it with `new Date()`. I'll have a look in the next few days.
