### ISSUE TITLE
Unicode Emojii Values break the session cookie JSON file

### ISSUE THREAD

**Issue by ammuench** [chill117/express-mysql-session#49]
Okay, so I know this sounds a bit crazy, but I'm currently running a site that uses Steam for OpenID, and part of that is that it passes back their steam username, which is serialized in the session.

We had a user who's cookie JSON was continually stored as unfinished--it simply cut-off halfway through.  Turns out he had Unicode Emojii in his steam name that caused the cookie to just give up and stop there--causing a failure later when the website tried to read the session since it couldn't parse an invalid JSON file  (see attached images).  

I'm not sure where it's failing in the process, but it appears that when a unicode emojii gets passed through, the cookie stops being written completely and is sent incomplete (note that the JSON object gets cut off after the user's name, right where the unicode emojii start)

<img width="660" alt="steamuser" src="https://cloud.githubusercontent.com/assets/2099658/17826097/18141614-6633-11e6-99c8-255cff3c751b.png">
<img width="939" alt="steamloginsessionbroke" src="https://cloud.githubusercontent.com/assets/2099658/17826096/18100d26-6633-11e6-902f-980afb1ba7e8.png">

**Comment by chill117** [comment]
That's an interesting one. Can you check the sessions database table to see if the data is cut-off in the same place?

**Comment by ammuench** [comment]
Yes, when we had him re register it cut off where the Unicode emojis came
up every time

**Comment by chill117** [comment]
Hmmm.. It is most likely an issue with the database character encoding. Could you post here the exact character that is causing the issue?

**Comment by ammuench** [comment]
For my problem user it kept breaking on  (snake emojii).

I know this is absurd, haha, thank you for actually hashing it out with me.

**Comment by chill117** [comment]
I think [this](http://apps.timwhitlock.info/unicode/inspect/hex/1F33E) is it? It doesn't seem to be supported by my browser (chrome). If that isn't it, maybe you can find it here:
http://apps.timwhitlock.info/emoji/tables/unicode

**Comment by ammuench** [comment]
That is it.  Odd you can't see it, I'm on chrome and it renders fine, haha.

But yes, that is the character that the session object was breaking on

**Comment by chill117** [comment]
@ammuench Did you try the "utf8mb4" encoding for the `sessions` table's `data` field?

**Comment by ammuench** [comment]
Hey, I'm redoing registration again and I seem to be getting the same issue again :/
I'm on 1.2.0 and I've verified that the charset is set to utf8mb4
