### ISSUE TITLE
Remove dependency with mysql-connection-manager

### ISSUE THREAD

**Issue by fcarreiro** [chill117/express-mysql-session#50]
I think that the managing of connections is orthogonal to the objective of this module. The dependency with [mysql-connection-manager](https://github.com/chill117/mysql-connection-manager) could be decoupled by accepting, in the construction of the session object, either a connection (and use `#query`), a pool (and use `#query`) or a function which in turn is expected to return a connection. Then, the following would work:

```javascript
var connection = mysql.createConnection(options);
var sessionStore = new MySQLStore({}/* session store options */, connection);
```
```javascript
var pool = mysql.createPool(options);
var sessionStore = new MySQLStore({}/* session store options */, pool);
```
```javascript
var MySQLConnectionManager = require('mysql-connection-manager');
var manager = new MySQLConnectionManager(options);
function getConnection() { return manager.connection; }
var sessionStore = new MySQLStore({}/* session store options */, getConnection);
```

In any case, as we have been discussing in [this issue](https://github.com/chill117/mysql-connection-manager/issues/10) I think I'd recommend deprecating mysql-connection-manager, and this issue goes in that direction.

Actually, if the possibility of passing a `MySQLConnectionManager` itself was never documented, I'd just accept a connection or pool (which are "the same" if you just use `#query` and similar).

I am happy to change the code and submit a pull request, if you agree with this.

**Comment by chill117** [comment]
This sounds good to me.

**Comment by fcarreiro** [comment]
With or without `function` support as a parameter? :)

**Comment by chill117** [comment]
I am not so sure about the function support idea. Let's leave it out for now.

**Comment by fcarreiro** [comment]
Ok! I'll try to do this when I have some time, and get back to you.

**Comment by chill117** [comment]
Great, thank you!
