### ISSUE TITLE
How do I best delete/expire all session of a given user (after a password reset)

### ISSUE THREAD

**Issue by mitomm** [chill117/express-mysql-session#53]
First of all, thanks for the great library.

As the title suggest, I want to expire all session of a given user after he has performed a password reset.

Since the userID is stored in the data field in mysql, I would be extremely inefficient to check each row and delete/expire all rows with the matching userID (since the data column is a JSON string that isn't indexed by userID).

I guess an easy solution would be to stroe the userID as a separate column inside the session table, however, I'm not sure how to fill that column then. Since the other fields are all automatically handled by express-mysql-session?

Maybe there is another obvious solution that I just don't see right now?

Thanks for you help.

**Comment by chill117** [comment]
You are on the right track. You would add a new indexed column to your sessions table (for the user ID). Then wherever you have your login logic, you would add an extra step where you update the new logged-in session with the user's ID in this new column. This wouldn't help you with existing logged-in sessions, but you could write a script to be run once on your database to update all existing sessions with the user ID (from the session's data field).

Hope that helps. Good luck!

**Comment by mitomm** [comment]
Alright, I'll try that. 

Thanks.

**Comment by Kyoloro** [comment]
+1, thanks.
