### ISSUE TITLE
Question: work with existing MySQL database & its connection

### ISSUE THREAD

**Issue by Jamsek-m** [chill117/express-mysql-session#56]
Hello,
I was hoping you could tell me what am I doing wrong when I try to use this module with my app.
I have a database I use for this express app already in place, and i would like that sessions are just one table in it.
I have a module for database db.js:
```
var mysql = require('mysql');
var connection = mysql.createPool({
    connectionLimit : 10,
    multipleStatements : true,
    host : 'localhost',
    user : 'username',
    password : 'pass',
    database : 'my_db'
});

connection.getConnection(function(err){
    if(err) throw err;
});

module.exports = connection;

//I am then able to use it like that in other files:
var db = require('./db);
db.query(...)
```

Now, when i tried to use your module to store my session (i use var req.session.user which holds all info of currently logged in user) I have a problem, because it keeps saying that it cannot read property 'user' of undefined - which means session is not created. 

I have this in app.js file:
```
var db = require('./db');
var session = require('express-session');
var MySQLStore = require('express-mysql-session')(session);

var sesStore = new MySQLStore({}, db);

app.use(session({
	secret : "EETTZUUZKJGFD",
	name : "my_site",
	saveUninitialized : true,
	resave : true,
	store : sesStore,
	cookie : {
		maxAge : 3600000
	}
}));
```

I would really appreciate the help, thank you

**Comment by chill117** [comment]
From the code you've posted, nothing jumps out at me as incorrect. Most likely your custom code that gives the undefined error is running before the session middleware.

**Comment by Jamsek-m** [comment]
I see, (I apologize to bug you, but i am fairly new to this). With this store, i still use session variable the same way (req.session.user)? and also, if i don't put those extra option on my db config, what will it default to? will table need to be created manually or..?

**Comment by chill117** [comment]
Passing in a database connection (as you are) should be enough. The database table will be created automatically, assuming the database connection has privileges to do so.

**Comment by Jamsek-m** [comment]
> assuming the database connection has privileges to do so.
and exactly that was the problem. Thank you very much for the help
