### ISSUE TITLE
Resave & Debugging performance issues

### ISSUE THREAD

**Issue by logidelic** [chill117/express-mysql-session#61]
I noticed that my server was performing poorly when there were many simultaneous requests and finally tracked it down to using express-mysql-session. Specifically, I was on version 1.0.0 and I noticed that if I set resave:false in the session options, I no longer had the problem. However, I saw that express-mysql-session 1.0.0 did support touch, and therefore was unsafe to use with resave:false. I upgraded to 1.2.0, but now the performance issues are back.

Questions:

- How can I debug performance issues with express-mysql-session?

- Why do the docs show a sample config with resave:true? Shouldn't this be set to false if express-mysql-session supports touch?

**Comment by chill117** [comment]
> Why do the docs show a sample config with resave:true? Shouldn't this be set to false if express-mysql-session supports touch?

You are correct. It looks like the express session module recommends `resave: false` if the session store supports the touch method. I will update the examples in the readme.

> How can I debug performance issues with express-mysql-session?

I haven't done any benchmarking on this module's methods. I would be happy to review and merge any such pull request, if you have the time to create one.

**Comment by chill117** [comment]
I created a benchmark for the touch method. With or without the `LIMIT 1` doesn't seem to affect performance that much. The performance issue could be with the express-sessions module or perhaps with other methods than touch.

**Comment by logidelic** [comment]
Thanks for the quick and useful response! After a bit of playing, it is clear that the issue is simply too many calls to UPDATE (one per request by the same session), slowing down my MySQL DB.

Obviously this is not a bug, however, I feel like there is room for a cheap optimization here. Is there any way in MySQLStore:touch to determine when the last touch was performed for that session? It would be great if we could configure the minimum interval between updates for the same session. Even changing this to ~1 second would eliminate the problem...

**Comment by chill117** [comment]
This is a simple layer to store sessions from the [express-sessions module](https://github.com/expressjs/session) into a MySQL database. I feel this type of optimization would be better handled higher up in the sessions module.

My suggestions:
* Use a higher performing store mechanism for your sessions (Redis is a good one, [connect-redis](https://github.com/tj/connect-redis))
* Wrap the session store's touch method so that you can handle the rate-limiting you've described

**Comment by logidelic** [comment]
I've taken your suggestion and did my own wrapper around touch, just because it was the quickest "solution". Works just fine now. Going forward I will indeed investigate Redis and other higher performing stores. I wonder if a warning/note should be added to the docs to point out that MySQL may not be an appropriate session store for high traffic sites?

Thanks again!
