### ISSUE TITLE
Change database connection when user needed to do so

### ISSUE THREAD

**Issue by calebeaires** [chill117/express-mysql-session#64]
I have on app project that connect to a distinct MySQL by user demand. This application use MySQL session to create temporary tables per MySQL distinct database connection. I have i have succeeded created session when app starts, but this app really need to change the [session store implementation](https://expressjs.com/en/resources/middleware/session.html#compatible-session-stores) module when a different MySQL connection is need by user. 

1. First -> create app and implement session store middleware like express documentation
2. Tried to change session store on router demand

I have tried to change the **session store** like this:

```node
router.get('/v1/:databaseName', function (req, res, next) {

    const databaseName = req.params.databaseName

    const options = {
	host: 'localhost',
	port: 3306,
	user: 'root',
	password: 'root',
	database: databaseName
     };

    const sessionStore = new MySQLStore(options);

    req.session.save(function () {
        req.session.store = sessionStore
        // do things from here
    });

});
```
So, how to use session store module on demand?

**Comment by chill117** [comment]
That sounds like a lot of overhead. Are you sure you don't want to revisit your application architecture?

**Comment by calebeaires** [comment]
I have made an singleton to save mysql connection_id to handle this issue.
