### ISSUE TITLE
Update from mysql@2.13.0 to 2.14.*

### ISSUE THREAD

**Issue by silverbackdan** [chill117/express-mysql-session#65]
Is it simple enough to update the mysql dependancy to 2.14.0 or 2.14.1 ? Will it cause any knock-on consequences?
https://snyk.io/vuln/npm:mysql:20170317

Low risk vulnerability discovered in 2.13.0

**Comment by chill117** [comment]
As long as tests still pass, it should be fine.

**Comment by silverbackdan** [comment]
Great stuff, closing this issue in favour of the PR https://github.com/chill117/express-mysql-session/pull/66 - updated package.json - that's all. Tests pass. Cheers!
