### ISSUE TITLE
Store should not .end() connection if using existing connection that it didn't create

### ISSUE THREAD

**Issue by mo** [chill117/express-mysql-session#70]
When the store is initialized with an existing database connection, like this:

```new MySQLStore({...}, connection);```

...then it should not call .end() on the connection from .close(). Whoever created the connection should be responsible for cleaning it up.

**Comment by chill117** [comment]
This one I agree with. Do you have time to create a pull request?

**Comment by chill117** [comment]
Done and will be included in the next release.
