### ISSUE TITLE
Not supporting MySQL 5.5.2 and older

### ISSUE THREAD

**Issue by zhangbenber** [chill117/express-mysql-session#73]
This library does not support MySQL 5.5.2 and older since it creates tables using `utf8mb4`, which is not supported by older versions of MySQL.

I created the table by myself using `utf8_bin`, and it seems working for me. However, this conflicts with Issue #49, will you add MySQL version detecting before creating the table, or at least, add a `Compatibility` section in README, and provide a `collation` option for some workarounds?

**Comment by chill117** [comment]
Looks like the utf8mb4 collation [was added in MySQL 5.5.3](Changes in MySQL 5.5.3 (2010-03-24, Milestone 3)) in early 2010. That's a long way back. Can you not upgrade your MySQL version?

**Comment by zhangbenber** [comment]
@chill117, I agree with you and I am considering updating my MySQL. But I didn't see any warnings or tips about what happened, and it confused me.

I suggest a tip in README may help it better. Thank you all the same.

**Comment by chill117** [comment]
@zhangbenber Yes, it would be nice to somehow save the next person some time either with a note in the readme about the collation or better yet a check (and warning) in the module itself if the old version (or a lack of proper collation support) is detected.

**Comment by chill117** [comment]
Added a note to the readme.
