### ISSUE TITLE
mariadb compatibility

### ISSUE THREAD

**Issue by pairmix** [chill117/express-mysql-session#77]
Hi there,
Is this module compatible with mariadb ?

**Comment by mattbrunetti** [comment]
This package uses `'mysql'` package, so the answer to your question would depend on if *that* is compatible with mariadb.. That said, I've been using the `'mysql'` package against a mariadb database for some basic functions, without any problems.

```
> SELECT VERSION();
10.0.28-MariaDB-wsrep
```

**Comment by chill117** [comment]
@pairmix This module should work with whatever the [mysql module](https://github.com/mysqljs/mysql/) is compatible - which looks to support and be compatible with MariaDB (see the [travis config](https://github.com/mysqljs/mysql/blob/3f371ca18a46150fc1fe1b8bb31a099b9f62f2fb/.travis.yml#L28-L35) file).
