### ISSUE TITLE
expiration is always default

### ISSUE THREAD

**Issue by gbacskai** [chill117/express-mysql-session#80]
I hope this helps:

from:
node_modules/express-mysql-session/index.js:			this.setExpirationInterval();
to:
node_modules/express-mysql-session/index.js:			this.setExpirationInterval(this.options.expiration);

**Comment by gbacskai** [comment]
as well

if (!expires) {
                        var dateObj = Date.now();
                        dateObj += this.options.expiration;
                        expires = new Date(dateObj);
                }

**Comment by gbacskai** [comment]
the cookie still always expire at the end of the session and not in the feature

**Comment by chill117** [comment]
The `expiration` option in this module is the maximum age of a valid session (in milliseconds). This applies only to the sessions stored in the MySQL database table. It has no effect on your session cookies. I think you are looking for the [cookie.maxAge option](https://github.com/expressjs/session#cookiemaxage) in the express-session module.

**Comment by popatop15** [comment]
I don't mean to bring old issues back to life, but the title nails my problem right on the head. I'm having trouble getting the module to set the correct session expiration. 

Here is my config object:
```js
const sessiondbconfig = {
    host: process.env.DB_HOST,
    port: process.env.DB_PORT,
    user: process.env.DB_USER,
    password: process.env.DB_PASSWORD,
    database: process.env.DB_NAME,
    schema: {
	    tableName: 'sessions',
	    columnNames: {
		    session_id: 'sid',
		    expires: 'expires',
		    data: 'session'
	    }
    },
    clearExpired: true,
    checkExpirationInterval: 900000,
    expiration: 86400000
};
```
And this is what is inserted into the database on session creation:
![image](https://user-images.githubusercontent.com/9933256/47882254-e5afd800-ddf6-11e8-9e7d-6235727ed461.png)

**Comment by chill117** [comment]
No worries. Good to hear that you figured it out :)
