### ISSUE TITLE
The array parameter in the callback method of store.all lacks the sessionid

### ISSUE THREAD

**Issue by huitouke120** [chill117/express-mysql-session#81]
I called the store.all method to find that the session object within the array in the callback method is missing sessionid, and is recommended. I have modified the code based on your code.

**Comment by chill117** [comment]
It looks like express-session expects the Store.all method to return all the sessions as an object where the keys are the session IDs. For example:
```json
{
    "session_id": {
        "some": "data..."
    },
    "session_id2": {
        "some": "other session here..."
    }
}
```

References:
* https://github.com/expressjs/session/blob/acd6049e4f4afdb56baf0ed84cfba5adccc9ef59/test/session.js#L151-L154
* https://github.com/expressjs/session/blob/8e57b21bef0d53010c4d37f4beee3f0341f3eaa6/session/memory.js#L58-L69

I've made the necessary changes to the all method in this module.

**Comment by chill117** [comment]
Included in latest release
