### ISSUE TITLE
Drop LIMIT 1 clause from UPDATE query

### ISSUE THREAD

**Issue by gcampax** [chill117/express-mysql-session#82]
Using LIMIT 1 causes MySQL to warn in certain configurations:

[Warning] Unsafe statement written to the binary log using statement format since BINLOG_FORMAT = STATEMENT. The statement is unsafe because it uses a LIMIT clause. This is unsafe because the set of rows included cannot be predicted. Statement: UPDATE `sessions` SET `expires` = 1524671478 WHERE `session_id` = '.......' LIMIT 1

The LIMIT clause is unnecessary anyway because session_id is PRIMARY KEY so the SQL optimizer knows there can be at most only one row touched.

**Comment by chill117** [comment]
This issue has been addressed by commit [2e21653](https://github.com/chill117/express-mysql-session/commit/2e21653484d1e3e5184e4341cff56612e4e53aad)
