### ISSUE TITLE
Bug in error message Failed to parse data for session

### ISSUE THREAD

**Issue by Feverqwe** [chill117/express-mysql-session#85]
Hello! Small bug is error message.

https://github.com/chill117/express-mysql-session/blob/67d123d343b607050d8cee01e6ca1d15145db4be/index.js#L172
Need replace to
```js
return cb(new Error('Failed to parse data for session:' + session_id)); 
```

**Comment by chill117** [comment]
Thanks for the heads-up! I've corrected the issue with commit [7a14107](https://github.com/chill117/express-mysql-session/commit/7a1410798e1bc7e351c2ce52b92544f18a07dd45).
