### ISSUE TITLE
Support for connection/pool option queryFormat

### ISSUE THREAD

**Issue by ddykhoff** [chill117/express-mysql-session#92]
Would it be possible to support the `queryFormat` option on connections/pools? Currently it throws an error for some custom query formats due to the internal SQLs of this package not abiding by the expected format when we want to reuse existing connections or pools.

https://github.com/mysqljs/mysql#custom-format

    const config = {
      database: process.env.SQL_DATABASE,
      password: process.env.SQL_PASSWORD,
      queryFormat: (query, values) => {
        if (!values) { return query; }
        return query.replace(/@(\w+)/g, (txt, key) => {
          if (values.hasOwnProperty(key)) {
            return mysql.escape(values[key]);
          }
          return txt;
        });
      },
      timezone: 'UTC',
      user: process.env.SQL_USER
    };
    
    const pool = mysql.createPool(config);
    const sessionStore = new MySqlStore({
      expiration: SESSION_LENGTH_MS, // session expiration from server side
      schema: {
        tableName: 'tbl_sessions',
        columnNames: {
          session_id: 'session_id',
          expires: 'expires',
          data: 'data'
        }
      }
    }, pool);
    
    app.use(session({
      secret: SESSION_SECRET,
      store: sessionStore,
      resave: false,
      saveUninitialized: false,
      cookie: {
        httpOnly: true, // restrict cookie access to http only (i.e. no js access)
        secure, // use secure cookies in prod
        maxAge: SESSION_LENGTH_MS // cookie expiration on client
      },
      genid: () => uuid()
    }));

Here is the error thrown with this configuration:

    Error: ER_PARSE_ERROR: You have an error in your SQL syntax; check the manual that 
    corresponds to your MySQL server version for the right syntax
    to use near '?? AS data, ?? as expires FROM ?? WHERE ?? = ?' at line 1

**Comment by chill117** [comment]
The queryFormat option appears to be unique per connection object. So I suggest to :
* Instantiate a separate connection object for express-mysql-session without the queryFormat option
* Or to not provide a connection object - only provide the db credentials in the options to express-mysql-session

**Comment by ddykhoff** [comment]
Yes, I had previously implemented something like your first suggestion and it appears to be working fine.

A lot missing from this snippet but the general idea is: 

    class Executor {
	  public static getRawConnection = (): Connection => {
        let rawConfig = { ...config }
        delete rawConfig.queryFormat
        return mysql.createConnection(rawConfig)
      }
	}
	
	const sessionStore = new MySqlStore({
      expiration: SESSION_LENGTH_MS, // session expiration from server side
      schema: {
        tableName: 'tbl_sessions',
        columnNames: {
          session_id: 'session_id',
          expires: 'expires',
          data: 'data'
        }
      }
    }, Executor.getRawConnection())
