### ISSUE TITLE
Enforce ARRAY outFormat

### ISSUE THREAD

**Issue by fhahne** [chill117/express-mysql-session#98]
Great module. One small tweak: could you enforce outFormat: oracledb.ARRAY for all the execute calls that rely on arrays as return value? I am running the store in a context where the global outFormat of the oracledb module gets overwritten, and thus the parsing of the session string fails.
E.g., in row 144 of index.js:
this.connection.execute(sql, params, { fetchInfo: { "DATA": { type: oracledb.STRING} } },
instead, use
this.connection.execute(sql, params, { outFormat: oracledb.ARRAY, fetchInfo: { "DATA": { type: oracledb.STRING} } },
Thanks,
Florian

**Comment by chill117** [comment]
Hello, @fhahne 
Are you sure that you are using this module? The code you've cited doesn't exist in this project.

**Comment by fhahne** [comment]
That is odd. Meant to post this to the express-oracle-session GitHub page. Looks like they forked from your project. No clue how my issue request ended up here, though. Sorry for the spam.
Florian
